### PR TITLE
Added WKWebView demo

### PR DESCRIPTION
**Pull request by basememara**
The cache doesn't seem to be working with `WKWebView`. I turned off the internet and the `UIWebView` still worked, but not the `WKWebView`.

### CODE REVIEW

**Comment by evermeer** [comment]
Sorry, WKWebView does not use the Cocoa stack with NSProtocol, NSUrl, NSUrlCache. When using WKWebView there is no alternative to do anything similar. (as far as I know)

For more info see for instance:
http://stackoverflow.com/questions/29573840/wkwebview-and-nsurlcache-to-serve-local-content

**Comment by basememara** [comment]
Thx for looking into this and the reply. Bummer, the `WKWebView` is irritating and haven't heard anything good about it. Sure it's "faster and more secure", but Apple still can't get this control right. I guess we'll have to give them another chance with iOS 10 :(

**Comment by evermeer** [comment]
We still use UIWebview. It's more than good enough in where we use it for.

**Comment by evermeer** [comment]
WKWebview can not be supported by EVURLCache

**Pull request closed without merging**
